version: '3.8'

services:
  nextjs-app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000/
    networks:
      - nextjs-net

networks:
  nextjs-net:
    driver: bridge
